version: "2"
linters:
  enable:
    - gocritic
  settings:
    gocritic:
      enabled-checks:
        - dupImport
        - nestingReduce
        - unnamedResult
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
